### PR TITLE
Fix Twisted Edge audio

### LINKED ISSUE #285: Twisted Edge Extreme Snowboarding no audio
There is a cheat in Project64 that makes it work:

```
"exhalatio audio hack",81051840 AD99
```

And in the AziAudio plugin it was fixed this way:
https://github.com/Azimer/AziAudio/pull/181/commits/7140f74be33615b4f9c62164e5e7e4d261cc6e48

I tried both methods in mupen64plus without success, still no audio

### PR DESCRIPTION
**Pull request by loganmc10**
Fixes #285 

This is a combination of these 2 commits:
https://github.com/project64/project64/commit/f24c464f3f8783dd9fdbeeaa21b02658c1340ec3

https://github.com/Azimer/AziAudio/commit/7140f74be33615b4f9c62164e5e7e4d261cc6e48

Firstly, AI_LEN_REG should be a multiple of 8, so I modified ```get_remaining_dma_length``` accordingly. This may fix other audio issues if they exist, I'm not sure. This is what allowed the audio samples to start getting sent to the audio plugin.

Secondly, Twisted Edge has some strange behaviour with AI_DRAM_ADDR_REG, it points to the wrong address. The "FixedAudioPos" hack takes the first AI_DRAM_ADDR_REG value, and uses that for the rest of the game, ignoring future values.

I compared to Project64 and it sounds the same to me.

### CODE REVIEW

**Comment by loganmc10** [comment]
This change (specifically making sure that ```get_remaining_dma_length``` returns a multiple of 8) also fixes the choppy engine sound in Top Gear Rally (https://github.com/mupen64plus/mupen64plus-core/issues/200) @fzurita

**Comment by fzurita** [comment]
Cool! I'll have to try it out.

File: src/device/ai/ai_controller.c [hunk 1]
```diff
@@ -139,12 +140,14 @@ void init_ai(struct ai_controller* ai,
...
              struct vi_controller* vi,
-             struct audio_out_backend* aout)
+             struct audio_out_backend* aout, unsigned int fixed_audio_pos)
 {
     ai->r4300 = r4300;
     ai->ri = ri;
     ai->vi = vi;
     ai->aout = aout;
+    ai->fixed_audio_pos = fixed_audio_pos;
+    ai->audio_pos = 0;
```
Comment (bsmiles32) [inline src/device/ai/ai_controller.c]: move ai->audio_pos = 0 in poweron_ai as it is a "state" variable and not a "configure" variable.

File: src/device/device.c [hunk 2]
```diff
@@ -53,7 +53,7 @@ void init_device(struct device* dev,
     uint16_t eeprom_id, struct storage_backend* eeprom_storage,
     struct clock_backend* clock,
     /* vi */
-    unsigned int vi_clock, unsigned int expected_refresh_rate, unsigned int count_per_scanline, unsigned int alternate_timing)
+    unsigned int vi_clock, unsigned int expected_refresh_rate, unsigned int count_per_scanline, unsigned int alternate_timing, unsigned int fixed_audio_pos)
```
Comment (bsmiles32) [inline src/device/device.c]: move fixed_audio_pos parameter upper in the parameter list be in the AI section please.

File: src/device/device.h [hunk 3]
```diff
@@ -78,7 +78,7 @@ void init_device(struct device* dev,
     uint16_t eeprom_id, struct storage_backend* eeprom_storage,
     struct clock_backend* clock,
     /* vi */
-    unsigned int vi_clock, unsigned int expected_refresh_rate, unsigned int count_per_scanline, unsigned int alternate_timing);
+    unsigned int vi_clock, unsigned int expected_refresh_rate, unsigned int count_per_scanline, unsigned int alternate_timing, unsigned int fixed_audio_pos);
```
Comment (bsmiles32) [inline src/device/device.h]: same here

File: src/main/main.c [hunk 4]
```diff
@@ -1065,7 +1065,7 @@ m64p_error main_run(void)
                 gb_carts,
                 (ROM_SETTINGS.savetype != EEPROM_16KB) ? 0x8000 : 0xc000, &eep_storage,
                 &clock,
-                vi_clock_from_tv_standard(ROM_PARAMS.systemtype), vi_expected_refresh_rate_from_tv_standard(ROM_PARAMS.systemtype), count_per_scanline, alternate_vi_timing);
+                vi_clock_from_tv_standard(ROM_PARAMS.systemtype), vi_expected_refresh_rate_from_tv_standard(ROM_PARAMS.systemtype), count_per_scanline, alternate_vi_timing, ROM_PARAMS.fixedaudiopos);
```
Comment (bsmiles32) [inline src/main/main.c]: same

File: src/plugin/emulate_speaker_via_audio_plugin.c [hunk 5]
```diff
@@ -53,6 +53,11 @@ void push_audio_samples_via_audio_plugin(void* user_data, const void* buffer, si
 
     /* exploit the fact that buffer points in g_dev.ri.rdram.dram to retreive dram_addr_reg value */
     ai->regs[AI_DRAM_ADDR_REG] = (uint8_t*)buffer - (uint8_t*)ai->ri->rdram.dram;
+    if (ai->fixed_audio_pos) {
```
Comment (bsmiles32) [inline src/plugin/emulate_speaker_via_audio_plugin.c]: This logic shouldn't be here as it is only meant as a "compatibility layer" to use zilmar spec audio plugins. Not a core behavior. This should go in write_ai_regs. Just add a case AI_DRAM_ADDR_REG in there and these lines.

**Comment by bsmiles32** [comment]
Did a quick review of this PR. While it fixes a known issue, I don't like these kind of hacks as I feel it is a missed opportunity for improve emulation accuracy. Still I won't object to merge it when it's ready. Good job none the less !!!

**Comment by loganmc10** [comment]
Ok I've updated the PR. I agree that a hack is not ideal. At least it's fairly non-intrusive/small. Hopefully somebody in the future can figure out how it should work properly.
